### ISSUE TITLE
Concepts Page doesn't give any context on how garderner works

### ISSUE THREAD

**Issue by robin-coac** [gardener/website-generator#191]
Documentation issue at https://gardener.cloud/docs/gardener/concepts/

Shouldn't the concepts page be more navigable. For someone new, I can't tell how to browse this.

**Comment by vlerenc** [comment]
What specifically do you find lacking/missing, see e.g. https://gardener.cloud/docs/gardener/concepts/architecture.

**Comment by robin-coac** [comment]
Appreciate this quick response !!


## FeedBack 1
I went through that architecture as well as this youtube video :
How Gardener helps organisations run Kubernetes multi-cloud? (at Multi Cloud Meetup - Kickoff)

When I go into this concepts page, I assume things are listed in order with a brief description provided of what it is.
Like : 
https://fluxcd.io/flux/concepts/
https://kubernetes.io/docs/concepts/

We Garderner makes is difficult and the page only provides a list of links.

## FeedBack 2

Also, Documentation could be more explicit. I couldn't find details of where exactly seed-cluster runs. I get that, there's this garder cluster where gardener controller runs. Then we manage clusters through the gardener UI. 

If I add a aws cluster to garderner, is it now both seed as well as shoot cluster ?
