### ISSUE TITLE
Improve the formatting of `Page Not Found` page

### ISSUE THREAD

**Issue by JordanJordanov** [gardener/website-generator#212]
**What would you like to be added**:
We need to advertise the suggestions (if we have such) in the error page. 
- The `Page Not Found` tile should be smaller font-size
- The focus should be on the suggestion (whatever this measn, e.g. bold, bigger font)

**Why is this needed**:
People hitting a moved page do not recognize easily that they have suggestions for where the page might be moved.

**Comment by Kostov6** [comment]
I will hand over this issue to @n-boshnakov and provide support if needed
