### ISSUE TITLE
Support the new GitHub Notes syntax

### ISSUE THREAD

**Issue by Kostov6** [gardener/website-generator#222]
**What would you like to be added**:
From https://gardener.cloud/docs/gardener/deployment/image_vector/ lets render the following correctly 

```
[!IMPORTANT] When the overwriting file contains ref for an image but the source file doesn’t, then this invalidates both repository and tag of the source. When it contains repository for an image but the source file uses ref, then this invalidates ref of the source.
```
**Why is this needed**:
Better visuals

**Comment by ialidzhikov** [comment]
/assign @RadaBDimitrova 
for the hugo version update

**Comment by ialidzhikov** [comment]
Starting [hugo@v0.134.0](https://github.com/gohugoio/hugo/releases/tag/v0.134.0) hugo is supposed to support the new Github styled alerts.
