### ISSUE TITLE
Wrong repository names in the graphic in README

### ISSUE THREAD

**Issue by berendt** [gardener/website-generator#48]
In the graphic ``kubernetes/documentation``, ``kubernetes/gardener-generator``, and ``kubernetes/gardener`` are used.

``kubernetes`` should be ``gardener``.

Unfortunately I don't have a sketch license, so I can't adapt it.

**Comment by g-pavlov** [comment]
Yes indeed, we are changing the whole process underneath and the image is not entirely adequate anyway as of today. We will probably change it entirely

**Comment by berendt** [comment]
@g-pavlov Are there any details about the upcoming changes already somewhere?

**Comment by g-pavlov** [comment]
@berendt in issues labeled kind/epic, mostly in the gardener/docforge. But right now I'm doing some house keeping, moving the process-related epics here. The idea is to stage the change process and set some milestones to have a live roadmap that the community can consider. Hopefully I will be mostly done today with this. Wrt the process as it stands now, see this: https://github.com/gardener/website-generator/issues/50

**Comment by g-pavlov** [comment]
@berendt  You may want to check the concept that we are implementing, part of which is the build process: https://github.com/gardener/website-generator/issues/51 . I may need to revisit the details but the concept is still in tact.

**Comment by Kristian-ZH** [comment]
I think that the issue is arelady fixed
