### ISSUE TITLE
Documentation Engineering: Landscape Deployment Documentation

### ISSUE THREAD

**Issue by g-pavlov** [gardener/website-generator#53]
# Documentation Engineering

> Milestone stage in #51 

## Landscape Deployment Documentation

Each Gardener landscape consists of component in a certain version that collectively constitute a BoM for that landscape. Operators and users need to be able to access the documentation for the exact version of the components in the landscape, preferably efficiently, without searching for it among other components and versions not relevant for that landscape.

The documentation bundle for a landscape should be built automatically e.g. using the static Gardener component model.

The documentation should be published on a dedicated website and accessible via the landscape Dashboard UI.

This epic can be considered a special case and a subset of #52 .

**Comment by Kristian-ZH** [comment]
not anymore in the backlog
