### ISSUE TITLE
Create UI mockup for Landscape Documentation

### ISSUE THREAD

**Issue by g-pavlov** [gardener/website-generator#54]
### The Landscape Documentation (LD) UI

Is supposed to gather multiple microsites that consist of documentation separated by the components that the landscape is built from.

As a first step we would like to have a mockup version of the website UI and the way it is structured. For example how are the documentation components defined and how do we navigate trough each. Another thing for example is how the API references for each component is displayed. What is left to be decided is either we create a LD UI for each landscape instance or provide the possibility to navigate between them by a dropdown menu (even between versions that are "to be released"). From one side this depends on how the LDUI will be consumed from the Dashboard UI for example and other possible ways to get to the site. Such things should be taken in consideration.

**Comment by Kristian-ZH** [comment]
not anymore in the backlog
