### ISSUE TITLE
Implement landscape microsite theme and layouts

### ISSUE THREAD

**Issue by g-pavlov** [gardener/website-generator#55]
In parallel to #54, we can start developing a microsite that is able to be imported as a component along side with other microsites.
In order to achieve this we need a common theme and layout that has to be used by those microsites. 
As done criteria we expect to have multiple micro websites that use the same layout and theme and are imported into a 
a website (LDUI for example) that is combining them into one.

**Comment by Kristian-ZH** [comment]
not anymore in the backlog
