### ISSUE TITLE
Integrate microsites in framework

### ISSUE THREAD

**Issue by g-pavlov** [gardener/website-generator#56]
To accomplish a Landscape Documentation UI that gathers multiple components (like Gardener, Gardener Dashboard, Machine Controller Manager and etc.) in the form of microsites, most simply we need a frame (header with navigation and footer) and we need a mechanism to combine those multiple microsites into one. In the end we should have a website that has different documentation components built separately.

**Comment by Kristian-ZH** [comment]
Not anymore in the backlog
