### ISSUE TITLE
Create project infrastructure

### ISSUE THREAD

**Issue by g-pavlov** [gardener/website-generator#58]
This is an umbrella issue that is meant to track the different steps to setup the project infrastructure.

- [ ] Create a dedicated repository that is going to manage the orchestration of the LDUI
- [ ] Add owners and contribution guide
- [ ] Manage permissions 
- [ ] Setup a pipeline definition for the CI/Cd
- [ ] Make the repository a component

**Comment by Kristian-ZH** [comment]
Not anymore in the backlog
