### ISSUE TITLE
Auto-assign reviewers based on content

### ISSUE THREAD

**Issue by g-pavlov** [gardener/website-generator#67]
Normally, repositories are configured to auto-assign code owners from the repo to PR reviews to that repo. When it comes to documentation, some processes require a documentation expert to be involved too. However, not every PR is strictly code or strictly documentation and normally documentation experts are not code-owners but rather play a cross repository function.

It would be beneficial to make auto-assign of reviewers smarter and if there are markdown documents in a PR, to assign a list of predefined documentation experts automatically too.

**Comment by Kristian-ZH** [comment]
not anymore in the backlog
